// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    CatalogTree: typeof import('./src/components/CatalogTree.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    EditArticle: typeof import('./src/components/EditArticle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTree: typeof import('element-plus/es')['ElTree']
    EndLoading: typeof import('./src/components/EndLoading.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RegisterAndLogin: typeof import('./src/components/RegisterAndLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagEditDialog: typeof import('./src/components/TagEditDialog.vue')['default']
    UserDetail: typeof import('./src/components/UserDetail.vue')['default']
  }
}
